{% set name = "phasespace" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zfit/phasespace/archive/{{ version }}.tar.gz
  sha256: ee5572dfd5a3912c31b5e3299f4882d3f65fb84d386404c6b3208138fabec581

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - tensorflow >=2.4,<=2.7
    - tensorflow-probability >=0.12,<=0.14

test:
  imports:
    - phasespace
    - phasespace.kinematics
    - phasespace.phasespace
    - phasespace.random

about:
  home: https://github.com/zfit/phasespace
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Phase space generation implemented in TensorFlow
  doc_url: https://phasespace.readthedocs.io
  dev_url: https://github.com/zfit/phasespace

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
