{% set name = "phasespace" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zfit/phasespace/archive/{{ version }}.tar.gz
  sha256: 80f17dcdb4ee00cdc0e050633b072a2ec295e19d3e31a23c2692d78fdf949154

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - tensorflow >=2.5,<2.6
    - tensorflow-probability >=0.11,<0.13

test:
  imports:
    - phasespace
    - phasespace.kinematics
    - phasespace.phasespace
    - phasespace.random

about:
  home: https://github.com/zfit/phasespace
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Phase space generation implemented in TensorFlow
  doc_url: https://phasespace.readthedocs.io
  dev_url: https://github.com/zfit/phasespace

extra:
  recipe-maintainers:
    - chrisburr
    - mayou36
