{% set name = "phasespace" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zfit/phasespace/archive/{{ version }}.tar.gz
  sha256: 5a49213012f716995e9c5824843faa1831cadb6744161338d18de99d1403fb9c

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - tensorflow >=2.0.0
    - tensorflow-probability
    # Workaround for https://github.com/conda-forge/tensorflow-probability-feedstock/pull/11
    - decorator
    - cloudpickle >=0.6.1

test:
  imports:
    - phasespace
    - phasespace.kinematics
    - phasespace.phasespace

about:
  home: https://github.com/zfit/phasespace
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Phase space generation implemented in TensorFlow
  doc_url: https://phasespace.readthedocs.io
  dev_url: https://github.com/zfit/phasespace

extra:
  recipe-maintainers:
    - chrisburr
    - mayou36
