{% set name = "phasespace" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/zfit/phasespace/archive/{{ version }}.tar.gz
  sha256: 1a368a8171c13110bc0aa78b721048ba9f3b7d7f2f56a8674092b58de58c7b48

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - tensorflow-base >=1.12.0
    - tensorflow-probability
    # Workaround for https://github.com/conda-forge/tensorflow-probability-feedstock/pull/11
    - decorator
    - cloudpickle >=0.6.1

test:
  imports:
    - phasespace
    - phasespace.kinematics
    - phasespace.phasespace

about:
  home: https://github.com/zfit/phasespace
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Physics extension to zfit
  doc_url: https://phasespace.readthedocs.io
  dev_url: https://github.com/zfit/phasespace

extra:
  recipe-maintainers:
    - chrisburr
    - mayou36
